name: Unload
on:
  push:
    branches:
      - main

env:
  JFROG_NAMESPACE: "cloudops"
  JF_URL: ${{ secrets.JF_URL }}
  JF_ACCESS_TOKEN: ${{ secrets.TOKEN }}

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.s3 }} # src = source / needed for uploads / [id returns output]
    defaults:
      run:
        working-directory: ./s3
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check
        uses: dorny/paths-filter@v3
        id: changes  #returns a value = outputs [id is github actions]
        with:
          filters: | 
            s3:
              - './s3/VERSION.txt'
  upload:
    needs: changes #changes is need by upload
    if: ${{ needs.changes.outputs.src == 'true' }} #if os for passing condition
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./s3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: jfrog/setup-jfrog-cli@v3 #Sets up jfrog-cli
      - name: Config
        run: |
          export SERVER_ID="masi32"
          jf c add $SERVER_ID --url=$JF_URL --access-token=$JF_ACCESS_TOKEN --interactive=false
          jf tfc --server-id-deploy $SERVER_ID --repo-deploy terraform-local-modules
          jf tf p --namespace=${JFROG_NAMESPACE} --provider=local --tag=$(cat VERSION.txt)
       # export sets variables that will be used in subsequent commands
       # p = publish
